const widget = document.querySelector('.widget');
const selectBtn = document.querySelector('.select');
const search = document.querySelector('.search input');
const options = document.querySelector('.options');
const countries = [
   "Afghanistan",
   "Albania",
   "Algeria",
   "Andorra",
   "Angola",
   "Antigua and Barbuda",
   "Argentina",
   "Armenia",
   "Australia",
   "Austria",
   "Azerbaijan",
   "Bahamas",
   "Bahrain",
   "Bangladesh",
   "Barbados",
   "Belarus",
   "Belgium",
   "Belize",
   "Benin",
   "Bhutan",
   "Bolivia",
   "Bosnia and Herzegovina",
   "Botswana",
   "Brazil",
   "Brunei",
   "Bulgaria",
   "Burkina Faso",
   "Burundi",
   "Cabo Verde",
   "Cambodia",
   "Cameroon",
   "Canada",
   "Central African Republic",
   "Chad",
   "Chile",
   "China",
   "Colombia",
   "Comoros",
   "Congo",
   "Costa Rica",
   "Croatia",
   "Cuba",
   "Cyprus",
   "Czechia",
   "Denmark",
   "Djibouti",
   "Dominica",
   "Dominican Republic",
   "Ecuador",
   "Egypt",
   "El Salvador",
   "Equatorial Guinea",
   "Eritrea",
   "Estonia",
   "Eswatini",
   "Ethiopia",
   "Fiji",
   "Finland",
   "France",
   "Gabon",
   "Gambia",
   "Georgia",
   "Germany",
   "Ghana",
   "Greece",
   "Grenada",
   "Guam",
   "Guatemala",
   "Guinea",
   "Guinea-Bissau",
   "Guyana",
   "Haiti",
   "Holy See",
   "Honduras",
   "Hong Kong",
   "Hungary",
   "Iceland",
   "India",
   "Indonesia",
   "Iran",
   "Iraq",
   "Ireland",
   "Israel",
   "Italy",
   "Jamaica",
   "Japan",
   "Jordan",
   "Kazakhstan",
   "Kenya",
   "Kiribati",
   "Korea",
   "Kuwait",
   "Kyrgyzstan",
   "Laos",
   "Latvia",
   "Lebanon",
   "Lesotho",
   "Liberia",
   "Libya",
   "Liechtenstein",
   "Lithuania",
   "Luxembourg",
   "Madagascar",
   "Malawi",
   "Malaysia",
   "Maldives",
   "Mali",
   "Malta",
   "Marshall Islands",
   "Mauritania",
   "Mauritius",
   "Mexico",
   "Micronesia",
   "Moldova",
   "Monaco",
   "Mongolia",
   "Montenegro",
   "Montserrat",
   "Morocco",
   "Mozambique",
   "Myanmar",
   "Namibia",
   "Nauru",
   "Nepal",
   "Netherlands",
   "New Zealand",
   "Nicaragua",
   "Niger",
   "Nigeria",
   "Norway",
   "Oman",
   "Pakistan",
   "Palau",
   "Palestine, State of",
   "Panama",
   "Papua New Guinea",
   "Paraguay",
   "Peru",
   "Philippines",
   "Poland",
   "Portugal",
   "Puerto Rico",
   "Qatar",
   "Romania",
   "Russia",
   "Rwanda",
   "Saint Kitts and Nevis",
   "Saint Lucia",
   "Saint Vincent and the Grenadines",
   "Samoa",
   "San Marino",
   "Sao Tome and Principe",
   "Saudi Arabia",
   "Senegal",
   "Serbia",
   "Seychelles",
   "Sierra Leone",
   "Singapore",
   "Slovakia",
   "Slovenia",
   "Solomon Islands",
   "Somalia",
   "South Africa",
   "South Sudan",
   "Spain",
   "Sri Lanka",
   "Sudan",
   "Suriname",
   "Sweden",
   "Switzerland",
   "Syria",
   "Taiwan",
   "Tajikistan",
   "Tanzania",
   "Thailand",
   "Timor-Leste",
   "Togo",
   "Tonga",
   "Trinidad and Tobago",
   "Tunisia",
   "Turkey",
   "Turkmenistan",
   "Tuvalu",
   "Uganda",
   "Ukraine",
   "United Arab Emirates",
   "United Kingdom",
   "United States",
   "Uruguay",
   "Uzbekistan",
   "Vanuatu",
   "Venezuela",
   "Viet Nam",
   "Yemen",
   "Zambia",
   "Zimbabwe",
];

function addCountries(selectedCountry) {
   options.innerHTML = '';
   countries.forEach(country => {
      let isSelected = country == selectedCountry ? 'selected' : '';
      let li = `<li onclick="updateName(this)" class="${isSelected}">${country}</li>`
      options.insertAdjacentHTML('beforeend', li);
   });
}

addCountries();

function updateName(selectedLi) {
   search.value = '';
   addCountries(selectedLi.innerText);
   widget.classList.remove('active');
   selectBtn.firstElementChild.innerText = selectedLi.innerText;
}

search.addEventListener('keyup', () => {
   let arr = [];
   let searchedVal = search.value;
   arr = countries.filter(data => {
      return data.toLowerCase().startsWith(searchedVal);
   }).map(data => `<li onclick="updateName(this)">${data}</li>`).join('');
   options.innerHTML = arr ? arr : `<p>Oops! Country not found</p>`;
})

selectBtn.addEventListener("click", () => {
   widget.classList.toggle('active');
})